/* SPDX-License-Identifier: GPL-3.0-or-later */
window.DemoData = {
  collections: [
    {
      id: "vale",
      name: "Wanderlight",
      image: "valley",
      subtitle: "Small companions. A wide world.",
      color: "#306f63",
    },
    {
      id: "coast",
      name: "Skybound",
      image: "coast",
      subtitle: "Follow the wind beyond the horizon.",
      color: "#366fa4",
    },
    {
      id: "orbit",
      name: "Orbit Post",
      image: "orbit",
      subtitle: "One more delivery among the stars.",
      color: "#715898",
    },
    {
      id: "multi",
      name: "Multiverse",
      image: "library",
      subtitle: "Your worlds beyond a single series.",
      color: "#a16b36",
    },
  ],
  games: [
    {
      id: "bloom",
      series: "vale",
      title: "Wanderlight",
      edition: "Bloom Trails",
      world: "The Glass Valley",
      image: "valley",
      platform: "GBA",
      year: "2004",
      genre: "Adventure · Collection",
      players: "1–2",
      online: true,
      color: "#34786d",
      description:
        "Follow the waterways of the Glass Valley. Befriend curious little companions, restore the old gardens and find a route to the observatory above the clouds.",
    },
    {
      id: "tide",
      series: "vale",
      title: "Wanderlight",
      edition: "Tide Almanac",
      world: "The Azure Coast",
      image: "coast",
      platform: "GBC",
      year: "2001",
      genre: "Adventure · Exploration",
      players: "1–2",
      online: true,
      color: "#467c9c",
      description:
        "An island almanac, an unfinished map and a companion who loves the sea. Discover the quiet stories hiding between the harbors.",
    },
    {
      id: "garden",
      series: "vale",
      title: "Wanderlight",
      edition: "Garden Stories",
      world: "The Lantern Garden",
      image: "garden",
      platform: "GBA",
      year: "2005",
      genre: "Puzzle · Adventure",
      players: "1",
      online: false,
      color: "#a55a75",
      description:
        "Bring a forgotten garden back to life. Each new friend has a small talent that makes this place a little more welcoming.",
    },
    {
      id: "sky",
      series: "coast",
      title: "Skybound",
      edition: "Paper Wings",
      world: "Windward Islands",
      image: "coast",
      platform: "SNES",
      year: "1996",
      genre: "Platform · Co-op",
      players: "1–2",
      online: true,
      color: "#3e72a5",
      description:
        "Sail on the afternoon breeze through a chain of floating harbors. Bring a friend for a shared journey across hand-crafted islands.",
    },
    {
      id: "cloud",
      series: "coast",
      title: "Skybound",
      edition: "Cloud Atlas",
      world: "The Upper Sea",
      image: "garden",
      platform: "GBA",
      year: "2003",
      genre: "Puzzle · Adventure",
      players: "1",
      online: false,
      color: "#8a5ea3",
      description:
        "Chart the clouds, repair your glider and solve the mysteries of an abandoned weather station.",
    },
    {
      id: "orbit",
      series: "orbit",
      title: "Orbit Post",
      edition: "Night Delivery",
      world: "The Astral District",
      image: "orbit",
      platform: "PS1",
      year: "1999",
      genre: "Adventure",
      players: "1",
      online: false,
      color: "#79609c",
      description:
        "Deliver letters to impossible addresses in a town suspended among the stars. There is always someone waiting for a little good news.",
    },
    {
      id: "rally",
      series: "multi",
      title: "Sunset Rally",
      edition: "Coastal Circuit",
      world: "The Open Road",
      image: "coast",
      platform: "PS1",
      year: "1998",
      genre: "Racing",
      players: "1–2",
      online: true,
      color: "#c17932",
      description:
        "Take the scenic route. Race along the coast with a friend, from the old harbor to the last light on the mountain.",
    },
    {
      id: "library",
      series: "multi",
      title: "Midnight Library",
      edition: "The Lost Index",
      world: "The Quiet Archive",
      image: "library",
      platform: "SNES",
      year: "1995",
      genre: "Puzzle",
      players: "1",
      online: false,
      color: "#785b89",
      description:
        "The books have rearranged themselves again. Untangle a gentle puzzle adventure through a library that changes after dark.",
    },
  ],
  creatures: [
    {
      id: "pip",
      name: "Pipkin",
      kind: "Meadow",
      color: "#efd279",
      number: "001",
      height: "0.4 m",
      weight: "5.2 kg",
      level: 24,
      hp: 42,
      max: 78,
      stats: [78, 56, 64, 42, 69, 51],
      description:
        "A patient little gardener. It carries seeds across the valley and curls up beside the warmest window.",
    },
    {
      id: "luma",
      name: "Luma",
      kind: "Twilight",
      color: "#bcaee1",
      number: "008",
      height: "0.6 m",
      weight: "3.1 kg",
      level: 22,
      hp: 33,
      max: 65,
      stats: [65, 40, 46, 82, 74, 88],
      description:
        "At dusk its soft light leads lost travelers home. It is especially fond of stories told very quietly.",
    },
    {
      id: "cora",
      name: "Coralie",
      kind: "Tide",
      color: "#f0b0b5",
      number: "014",
      height: "0.3 m",
      weight: "7.8 kg",
      level: 20,
      hp: 69,
      max: 69,
      stats: [69, 49, 81, 67, 75, 30],
      description:
        "Collects smooth stones and arranges them by color. Its delicate fins ripple like ribbons underwater.",
    },
    {
      id: "flint",
      name: "Flintlet",
      kind: "Quartz",
      color: "#aad8d9",
      number: "027",
      height: "0.7 m",
      weight: "12 kg",
      level: 26,
      hp: 54,
      max: 92,
      stats: [92, 80, 89, 43, 61, 48],
      description:
        "A bright-eyed explorer with a very soft step. The branches on its head chime gently in the wind.",
    },
  ],
  shops: [
    {
      name: "Valley Supply",
      subtitle: "Everyday essentials",
      items: [
        { name: "Trail tonic", price: 120, icon: "⚱", color: "#9bd0d4" },
        { name: "Berry biscuit", price: 60, icon: "✿", color: "#edb3bc" },
        { name: "Wayfarer kit", price: 240, icon: "▣", color: "#b9d8a1" },
      ],
    },
    {
      name: "Garden Exchange",
      subtitle: "Little treasures",
      items: [
        { name: "Moon seed", price: 90, icon: "✧", color: "#c8b4df" },
        { name: "Sun ribbon", price: 180, icon: "❋", color: "#f1d071" },
        { name: "Glass charm", price: 300, icon: "◆", color: "#99d2dc" },
      ],
    },
  ],
  explanations: {
    home: [
      "Home",
      "Ваше приключение — сразу перед вами",
      "Выбирайте серию стрелками, меняйте игру через Choose Adventure или нажмите большую кнопку запуска. Прогресс и команда относятся к выбранной игре.",
    ],
    worlds: [
      "Worlds",
      "Вся библиотека, без лишних шагов",
      "Откройте коллекцию, листайте названия слева и смотрите подробности справа. Play сразу запускает демонстрацию игры; ⋯ открывает управление.",
    ],
    guide: [
      "Companions / Guide",
      "Справочник рядом с приключением",
      "Выберите существо слева: иллюстрация, описание и цветные характеристики появятся на том же экране. Здесь — вымышленная коллекция для демо.",
    ],
    party: [
      "Companions / Party",
      "Ваша команда",
      "Нажмите на участника, чтобы посмотреть способности или отправить его в хранилище. Команда общая для этого демо: изменения видны на Home и полянке.",
    ],
    boxes: [
      "Companions / Boxes",
      "Хранилище без путаницы",
      "Выберите существо в коробке, чтобы вернуть его в команду. Здоровье в коробке не показывается. Эта сцена иллюстрирует работу с поддерживаемыми сохранениями.",
    ],
    center: [
      "Companions / Center",
      "Небольшая остановка перед дорогой",
      "Лечение оживляет всю команду, а Link Counter показывает обмен и дружеское сражение. В настоящей системе работа с сохранением зависит от адаптера конкретной игры.",
    ],
    playroom: [
      "Companions / Playroom",
      "Можно просто побыть вместе",
      "Спутники гуляют и отдыхают. Нажмите на любого, чтобы позвать; предложите угощение или начните пример совместной игры.",
    ],
    shops: [
      "Companions / Shops",
      "Покупки целой корзиной",
      "При выборе магазина сразу видны товары. Добавляйте нужное количество и оплачивайте всю корзину одним действием. Баланс и сумка в демо действительно меняются.",
    ],
    trainer: [
      "Trainer",
      "Профиль и история путешествий",
      "Измените имя, посмотрите памятные события и достижения. В демо награды вымышлены; в TrainerOS отдельная вкладка подключается к RetroAchievements.",
    ],
    social: [
      "Social",
      "Разговор продолжается, даже когда вы играете",
      "Выбирайте переписку и пишите прямо в строке ввода. Пример показывает приглашение друга в игру и общий звонок. Собеседники здесь — сценарные персонажи, сеть не используется.",
    ],
    settings: [
      "Start / Settings",
      "Настройки в одном месте",
      "Выберите раздел слева. Тема, анимации и имя меняют демо; сеть, громкость и оборудование показаны как локальные примеры, без доступа к вашему устройству.",
    ],
    game: [
      "Adventure / Home menu",
      "Игра и друзья остаются рядом",
      "Это иллюстративная сцена вместо эмулятора. Нажмите Home menu: можно пригласить друга, посмотреть настройки изображения и вернуться в игру без новой цепочки экранов.",
    ],
  },
};
